make_renderer_script <- function(settings, columns, custom_code = "") {
  settings_text <- paste(capture.output(dput(settings)), collapse = "\n")
  columns_text <- paste(capture.output(dput(columns)), collapse = "\n")
  extension <- if (nzchar(trimws(custom_code))) paste0("\n# Advanced Leaflet extensions (review before running).\n", custom_code, "\n") else ""
  paste0(
    "# Generated by Modular Mapping Studio.\n",
    "# Run from this folder: Rscript render_map.R\n",
    "# Required packages: leaflet, htmlwidgets, htmltools, sf\n\n",
    "source(file.path('R', 'map_helpers.R'))\n",
    "data <- utils::read.csv('data.csv', check.names = FALSE, stringsAsFactors = FALSE)\n",
    "polygons <- if (file.exists('polygons.geojson')) sf::st_read('polygons.geojson', quiet = TRUE) else NULL\n",
    "settings <- ", settings_text, "\n",
    "columns <- ", columns_text, "\n",
    "map <- build_leaflet_map(data, polygons, settings, columns)\n",
    extension,
    "htmlwidgets::saveWidget(map, 'map.html', selfcontained = TRUE)\n",
    "message('Wrote map.html')\n"
  )
}

write_project_bundle <- function(destination, data, polygons, settings, columns, custom_code = "") {
  work <- tempfile("mapping-export-")
  dir.create(work)
  dir.create(file.path(work, "R"))
  on.exit(unlink(work, recursive = TRUE), add = TRUE)

  utils::write.csv(data, file.path(work, "data.csv"), row.names = FALSE, na = "")
  if (!is.null(polygons) && nrow(polygons) > 0) {
    polygons <- sf::st_transform(polygons, 4326)
    sf::st_write(polygons, file.path(work, "polygons.geojson"), quiet = TRUE, delete_dsn = TRUE)
  }
  file.copy(file.path("R", "map_helpers.R"), file.path(work, "R", "map_helpers.R"), overwrite = TRUE)
  writeLines(make_renderer_script(settings, columns, custom_code), file.path(work, "render_map.R"), useBytes = TRUE)
  writeLines(c(
    "# Exported mapping project",
    "",
    "1. Install the R packages leaflet, htmlwidgets, htmltools, and sf.",
    "2. Run `Rscript render_map.R` from this folder.",
    "3. The renderer writes `map.html`; basemap tiles require an internet connection.",
    "4. Advanced Leaflet code is inserted into the renderer and is not run by the Shiny preview.",
    "5. The exported project does not contain the Azure Maps subscription key."
  ), file.path(work, "README.md"))

  files <- c("README.md", "data.csv", "render_map.R", "R/map_helpers.R")
  if (file.exists(file.path(work, "polygons.geojson"))) files <- c(files, "polygons.geojson")
  zip::zipr(zipfile = destination, files = files, root = work, include_directories = FALSE)
}
