export_project_config <- function(project) {
  config <- project
  config$datasets <- lapply(project$datasets, function(dataset) {
    dataset$data <- NULL
    dataset$file <- file.path("data", paste0(dataset$id, ".rds"))
    dataset
  })
  config
}

assert_no_exported_keys <- function(text, secrets = character()) {
  secrets <- unique(c(secrets, Sys.getenv("AZURE_MAPS_SUBSCRIPTION_KEY")))
  for (secret in secrets[!is.na(secrets) & nzchar(secrets)]) {
    if (grepl(secret, text, fixed = TRUE) ||
        grepl(utils::URLencode(secret, reserved = TRUE), text, fixed = TRUE)) {
      stop("Advanced code contains the Azure Maps key. Remove credentials before exporting.", call. = FALSE)
    }
  }
  invisible(TRUE)
}

make_renderer_script <- function(project, custom_code = "", secrets = character()) {
  if (is.null(custom_code)) custom_code <- ""
  assert_no_exported_keys(custom_code, secrets)
  extension <- if (nzchar(trimws(custom_code))) paste0(
    "\n# User-supplied Leaflet code; review before running this renderer.\n", custom_code, "\n") else ""
  paste0(
    "# Generated by Leaflet Map Studio. Run from the extracted project folder.\n",
    "# Requires: leaflet, htmlwidgets, htmltools, sf. Optional: leaflet.extras.\n",
    "for (file in c('project_model.R', 'map_palettes.R', 'map_popups.R',\n",
    "               'map_layers.R', 'map_builder.R', 'map_helpers.R')) {\n",
    "  source(file.path('R', file))\n",
    "}\n",
    "project <- readRDS('project.rds')\n",
    "for (id in names(project$datasets)) {\n",
    "  dataset <- project$datasets[[id]]\n",
    "  dataset$data <- readRDS(dataset$file)\n",
    "  dataset$file <- NULL\n",
    "  project$datasets[[id]] <- dataset\n",
    "}\n",
    "map <- build_leaflet_map(project)\n",
    extension,
    "htmlwidgets::saveWidget(map, 'map.html', selfcontained = TRUE)\n",
    "message('Wrote map.html')\n"
  )
}

write_project_bundle <- function(destination, project, helpers_dir = "R", custom_code = "",
                                 secrets = character()) {
  script <- make_renderer_script(project, custom_code, secrets)
  folder <- tempfile("leaflet-studio-")
  dir.create(folder)
  dir.create(file.path(folder, "R"))
  dir.create(file.path(folder, "data"))
  on.exit(unlink(folder, recursive = TRUE), add = TRUE)

  config <- export_project_config(project)
  saveRDS(config, file.path(folder, "project.rds"))
  for (id in names(project$datasets)) {
    saveRDS(project$datasets[[id]]$data, file.path(folder, config$datasets[[id]]$file))
  }
  helpers <- c("project_model.R", "map_palettes.R", "map_popups.R",
    "map_layers.R", "map_builder.R", "map_helpers.R")
  copied <- file.copy(file.path(helpers_dir, helpers), file.path(folder, "R", helpers))
  if (!all(copied)) stop("Could not copy the map helper functions into the ZIP.", call. = FALSE)
  writeLines(script, file.path(folder, "render_map.R"), useBytes = TRUE)
  writeLines(c(
    "# Exported Leaflet Map Studio project",
    "",
    "Install leaflet, htmlwidgets, htmltools and sf in R; leaflet.extras enables optional search/fullscreen widgets.",
    "From this extracted folder run `Rscript render_map.R` to write `map.html`.",
    "The project.rds file contains dataset/layer/map/widget/filter settings, without dataset copies.",
    "The data/*.rds files preserve both tabular and sf datasets, including CRS and column types.",
    "Base tiles need an internet connection, even in self-contained HTML exports.",
    "Advanced renderer code is included only if you entered it in the Export tab; review it before use.",
    "Azure Maps subscription keys are never stored in this project."
  ), file.path(folder, "README.md"))

  files <- c("README.md", "project.rds", "render_map.R",
    file.path("R", helpers), file.path("data", paste0(names(config$datasets), ".rds")))
  zip::zipr(zipfile = destination, files = files, root = folder,
    include_directories = FALSE, mode = "mirror")
  invisible(destination)
}

mod_export_ui <- function(id) {
  ns <- shiny::NS(id)
  shiny::tagList(
    shiny::textAreaInput(ns("advanced"), "Advanced Leaflet R code (optional)", rows = 4,
      placeholder = "map <- map |> leaflet::addScaleBar()"),
    shiny::helpText("Exported code runs only in the renderer, not in the preview. Do not include credentials."),
    shiny::downloadButton(ns("download_html"), "Download standalone HTML", class = "btn-primary"),
    shiny::br(), shiny::br(),
    shiny::downloadButton(ns("download_script"), "Download renderer script"),
    shiny::br(), shiny::br(),
    shiny::downloadButton(ns("download_bundle"), "Download project ZIP"),
    shiny::hr(),
    shiny::helpText("The renderer script expects project.rds, R/ helpers and data/ files from the ZIP. Basemap tiles are fetched online."),
    shiny::tags$details(shiny::tags$summary("Renderer script"),
      shiny::verbatimTextOutput(ns("generated_code")))
  )
}

mod_export_server <- function(id, project, azure_key = function() "", helpers_dir = "R") {
  shiny::moduleServer(id, function(input, output, session) {
    advanced <- shiny::reactiveVal("")
    shiny::observeEvent(input$advanced, advanced(input$advanced))

    output$generated_code <- shiny::renderText({
      make_renderer_script(project_list(project), advanced(), secrets = azure_key())
    })
    output$download_html <- shiny::downloadHandler(
      filename = function() "map.html",
      content = function(file) {
        render_map_html(shiny::isolate(project_list(project)), file, selfcontained = TRUE)
      }
    )
    output$download_script <- shiny::downloadHandler(
      filename = function() "render_map.R",
      content = function(file) {
        script <- make_renderer_script(shiny::isolate(project_list(project)),
          shiny::isolate(advanced()), secrets = shiny::isolate(azure_key()))
        writeLines(script, file, useBytes = TRUE)
      }
    )
    output$download_bundle <- shiny::downloadHandler(
      filename = function() "leaflet-map-project.zip",
      content = function(file) {
        write_project_bundle(file, shiny::isolate(project_list(project)),
          helpers_dir = helpers_dir, custom_code = shiny::isolate(advanced()),
          secrets = shiny::isolate(azure_key()))
      }
    )
  })
}
